### PR TITLE
fix: treat delay of undefined same as null

### PR DESCRIPTION
**Pull request by jedwards1211**

### CODE REVIEW

**Comment by johndiiorio** [comment]
Thank you for your pull request. I have incorporated these changes in the latest release. I opted to be more explicit about the check, I don't like using `==` or `!=`.

**Comment by jedwards1211** [comment]
Whatever sinks your ship

**Comment by jedwards1211** [comment]
You do know that `a != null` *is exactly equivalent to* `a !== null and a !== undefined` right?

**Comment by johndiiorio** [comment]
Of course, it's what it gets minifies to in the bundle. It's just not as clear.

**Comment by jedwards1211** [comment]
Sorry i was being a jerk about this.   Thanks for merging my logic change

**Comment by johndiiorio** [comment]
No problem. Let me know if you think anything else should be changed.

**Pull request closed without merging**
